### ISSUE TITLE
Create command for storing/fetching email addresses by slack user

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-hubot#12]
Slack allows emails to be public to all team members, but that is turned off (likely so as not to assume that all will want to share). We could add a command to store these away somewhere, for those who want to opt-in to sharing.

This is useful for gcal invites and the likes

Example:

```
patcon: halpy email me patrick.c.connolly@gmail.com
...
<time passes>
...
lourdesvera: email me @patcon
halpy: patcon's email is patrick.c.connolly@gmail.com
```

cc: @lourdesvera

**Comment by patcon** [comment]
Oops. Seems that the EDGI slack actually makes emails viewable:
https://edgi.slack.com/archives/C3EF5T7T6/p1493763822435785

So I'll close this for now. It might end up being useful if someone signed up with an email that they don't use for invites, and maybe thy want to indicate another. But I'll assume that's a minor concern until I hear otherwise :)

**Comment by dcwalk** [comment]
Hey! I'm one of those annoying people who maintains multiple emails and has certain ones for different things, but yeah-- I think that is a low priority :)
