### ISSUE TITLE
Deploy edgi-hubot to archivers slack

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-hubot#17]

**Comment by patcon** [comment]
Interestingly, there is less need for this when slackbridges are created, as people can talk to the bot through the bridge.

Since it's waaaaay simpler to re-use the bot (and therefore the bot use in both channels is 100% the same), I'm going to defer on this for now.

**Comment by dcwalk** [comment]
Is this something we want to close as `wont do` for now? (and does this relate to https://github.com/edgi-govdata-archiving/overview/issues/139)? It seems like we could close at least one issue if this is a low-priority?
