### ISSUE TITLE
Allow anyone to create zoom meetings from chat

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-hubot#9]
https://github.com/poynt/boynt/blob/master/scripts/zoom.coffee

Dawn suggested that this would be great for ad-hoc meetings. The other types of meetings EDGI uses often are recurring and pre-scheduled.

pre-scheduled would prob be simple to add, but not sure "recurring" would be simple to manage from chat. Plus, by definition, they just get set up once, and then rarely touched, so prob not good candidate to automation help ;)

**Comment by patcon** [comment]
Seems that I can start testing this now, as everyone gets s 60-day developer trial (which I need to get an API key): https://zoom.us/developer/overview/getting-started-with-rest-api

Eventually, I'll need to get an API key generated with our "Pro" (?) account.

**Comment by shapironick** [comment]
I can lastpass you one of our paid account passwords whenever you would
like.

**Comment by patcon** [comment]
Done and done for on-demand meetings.
